[project]
name = "logcli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jimison.chu@datacom.com.tw", email = "jimison.chu@datacom.com.tw" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.4",
    "rich>=15.0.0",
]

[project.scripts]
logcli = "logcli:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "ruff>=0.15.22",
]

[tool.ruff]
line-length = 100          # 一行最多幾字元
src = ["src"]              # 告訴 ruff 套件在 src/ 底下，import 排序才會正確

[tool.ruff.lint]
select = ["E", "F", "I"]   # E=pycodestyle 錯誤, F=pyflakes(未使用變數/import), I=isort(import 排序)

